package demo.specification;

import javax.persistence.criteria.Predicate;

import org.springframework.data.jpa.domain.Specification;

import demo.model.User;
import demo.model.User_;

public class CustomSpecifications {

	// Note: User_ is the @StaticMetamodel of the class User
	// generated by hibernate-jpamodelgen dependency
	// The source folder target/generated-sources/annotations must be
	// added to the buildpath (Project > Configure Build Path)
	public static Specification<User> hasLikesBetween(Integer lowerBound,
			Integer upperBound) {

		return (root, query, criteriaBuilder) -> {
			Predicate predicate = criteriaBuilder.conjunction();
			if (lowerBound != null) {
				predicate = criteriaBuilder.and(
						predicate,
						criteriaBuilder.greaterThanOrEqualTo(
								root.get(User_.likes), lowerBound));
			}
			if (upperBound != null) {
				predicate = criteriaBuilder.and(predicate, criteriaBuilder
						.lessThanOrEqualTo(root.get(User_.likes), upperBound));
			}
			return predicate;
		};
	}

}